Krish pointlistnew
awest25/Tennis-Video-Viewer pull request #110
Opened 2024-04-06 08:47 UTC by krish1925

Created point list based on figma, displaying the client and opposing logo and other match details

2024-04-10 17:24 UTC, awest25 requested changes

2024-04-10 17:24 UTC, awest25 commented on app/components/PointsList.js
It's not clear what the script tags do. For clarity, please add a comment or store the URLs in constant variables. Or figure out a clearer way to add the scripts.

> Inline <link> and <script> Tags: Loading Bootstrap or any external CSS/JS directly within a React component is unconventional. Typically, you'd include such resources in your HTML template (e.g., public/index.html in a Create React App project) or import them as modules in your JavaScript files if available in an npm package format. This ensures they are loaded once and available application-wide, avoiding potential duplication and conflicts.

`parsePointData` is being called every render of the JSX, seems inefficinet.

The cursor should indicate that the row is clickable with the little hand. The whole row should be clickable.

Please add the background gradient and use the same gray colors as in the figma.

These are relitiveley minor things and other than this, I like the RegEx and everything else. Thank you!

2024-04-11 23:32 UTC, krish1925 commented on app/components/PointsList.js
Thanks for the feedback, I was thinking of adding the scripts for Bootstrap styling to the main HTML, but I didn't want to make too many changes to different pages/ wasn't sure if you were fine using Bootstrap so I just kept it local so that it could be easily removed (if needed). I wasn't really sure that the entire row needed to be clickable (because of the button) so I removed that functionality, but I'll add that right back in.

 Okay I'll add the additional stuff that you've mentioned about it and make the changes before tomorrow's meeting. Thanks!

2024-04-14 00:12 UTC, krish1925 commented on app/components/PointsList.js
Added the logo functionality, however if match names are different then it won't work : first player must be with format " <player1> vs <othermetadataofmatch>" or "<player1> UCLA vs <othermetadataofmatch>" as it uses regex.

2024-04-15 05:47 UTC, awest25 submitted a review, later dismissed
<img width="966" alt="Screenshot 2024-04-14 at 10 46 27 PM" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/a3a9b7d0-e1f3-4d6c-bc27-b455ece3fe15">
It doesn't seem like it works on mobile?

2024-04-15 05:47 UTC, awest25 commented on app/(interactive)/matches/[slug]/page.js
As far as I can tell on this page, the team data is not being used for anything as it's not being passed into pointList. Also, you should be storing `setTeamsData({team1: team1Data, team2: team2Data});` not the entire teams collection. Then you can pass that into pointsList.

2024-04-15 05:47 UTC, awest25 commented on app/(interactive)/matches/[slug]/page.js
> +                  <PointsList pointsData={returnFilteredPoints()} onPointSelect={handleJumpToTime} matchDetails={matchData.matchDetails}  clientTeam={matchData.clientTeam} opponentTeam={matchData.opp
passing in the wrong props here, donesn't match the component.

2024-04-15 05:47 UTC, awest25 commented on app/components/PointsList.js
> +                <img src="https://icons.veryicon.com/png/o/miscellaneous/food-time/play-video-1.png" alt="Play Icon" style={{ maxWidth: '30px', height: 'auto', minWidth: '30px' }} />
Use an SVG instead of an image. The benifit is smaller filesize which means faster loading and they are infiniteley scalable. Save this in the `public/images/play-icon.svg` directory (or similar, not 100% sure how Next likes it) so it can be reused. Below is an example of one that may work. Putting this directly in the JSX instead of the <img> tag will let you try it out.

```JSX
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 30" x="0px" y="0px" style={{ width: '50px', height: '30px' }}>
  <title>play circle</title>
  <g data-name="play circle">
      <path d="M12,24A12,12,0,1,1,24,12,12,12,0,0,1,12,24ZM12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Z" stroke="grey" fill="grey" />
      <path d="M9,17 L16,12 L9,7 Z" fill="grey"/>
  </g>
</svg>
```

2024-04-15 05:48 UTC, awest25 commented
Also I'm not yet seeing the logos, pls double check what's going on

2024-04-15 18:43 UTC, Fredenck commented on app/(interactive)/matches/[slug]/page.js
to be specific, the firebase doc contains the field 'clientTeam' and 'opponentTeam'. This change was made to support future endeavors including filtering matches by school/team for scouting purposes, creating a personalized player dashboard with their matches, etc.

2024-04-23 06:54 UTC, Fredenck approved these changes
fixed

2024-04-23 06:56 UTC, merged