172 add new search bar
awest25/Tennis-Video-Viewer pull request #181
Opened 2024-08-28 22:10 UTC by kesdlvi

Implemented search bar for matches which uses a fuzzy search

For styling the search bar required its own component. I wasn't able to figure out how to use css.

The search just returns an array as requested, to see the output just `console.log(result)` in `Dashboard.js`

2024-08-29 06:07 UTC, awest25 requested changes
So I think that since we're revamping the upload functionality, we can go ahead and add a field to firebase upon upload that is an array of searchableProperties now. This is a separate issue so you could do that and come back to this.

2024-08-29 06:07 UTC, awest25 commented on app/components/Dashboard.js
> +            options={filteredMatches} // Use filtered matches as options
There should be no actual dropdown so no opitons prop i believe, and actually if you're trying to use CSS, you could just use a standard HTML5 search field or a react search field. This isn't nesseasary

And at this point could you make it so that if the player types something it refreshes the tile list each time a new character is added? And when they start typing a cancel button becomes visibe that, when clicked, erases the text box and hides the cancel button and removes the filter. (i've added thsi update to the issue as well)

To facilitate this, the search bar should permanently be ~30px higher, leaving a permanent gap between that and the event list, leaving room for the right-alined cancel button to show up.

2024-08-29 06:07 UTC, awest25 commented on app/components/SearchPlaceholder.js
Just go ahead and declare this component the dashboard file somewhere. This likeley wouldn't apply if you're not replacing react-select with just an input field.

2024-10-07 00:12 UTC, Fredenck approved these changes
Awesome work, I like what I see

2024-10-08 17:00 UTC, merged